services:

  auth-service:
    build:
      context: .
      dockerfile: ./auth-service/Dockerfile
      target: dev
    volumes:
      - ./auth-service/src:/app/auth-service/src
    command: sh -c "npx prisma migrate deploy --schema=/app/shared/prisma/schema.prisma && npm run start:dev"
    environment:
      CHOKIDAR_USEPOLLING: "true"

  product-service:
    build:
      context: .
      dockerfile: ./product-service/Dockerfile
      target: dev
    volumes:
      - ./product-service/src:/app/product-service/src
    command: sh -c "npx prisma migrate deploy --schema=/app/shared/prisma/schema.prisma && npm run start:dev"
    environment:
      CHOKIDAR_USEPOLLING: "true"

  order-service:
    build:
      context: .
      dockerfile: ./order-service/Dockerfile
      target: dev
    volumes:
      - ./order-service/src:/app/order-service/src
    command: sh -c "npx prisma migrate deploy --schema=/app/shared/prisma/schema.prisma && npm run start:dev"
    environment:
      CHOKIDAR_USEPOLLING: "true"

  payment-service:
    build:
      context: .
      dockerfile: ./payment-service/Dockerfile
      target: dev
    volumes:
      - ./payment-service/src:/app/payment-service/src
    environment:
      CHOKIDAR_USEPOLLING: "true"

  delivery-service:
    build:
      context: .
      dockerfile: ./delivery-service/Dockerfile
      target: dev
    volumes:
      - ./delivery-service/src:/app/delivery-service/src
    environment:
      CHOKIDAR_USEPOLLING: "true"

  analytics-service:
    build:
      context: .
      dockerfile: ./analytics-service/Dockerfile
      target: dev
    volumes:
      - ./analytics-service/src:/app/analytics-service/src
    environment:
      CHOKIDAR_USEPOLLING: "true"

  search-service:
    build:
      context: .
      dockerfile: ./search-service/Dockerfile
      target: dev
    volumes:
      - ./search-service/src:/app/search-service/src
    environment:
      CHOKIDAR_USEPOLLING: "true"

  api-gateway:
    build:
      context: .
      dockerfile: ./api-gateway/Dockerfile
      target: dev
    volumes:
      - ./api-gateway/src:/app/api-gateway/src
    environment:
      CHOKIDAR_USEPOLLING: "true"

  frontend:
    build:
      context: ./frontend
      target: dev
    volumes:
      - ./frontend/src:/app/src
    ports:
      - "5173:5173"
    environment:
      CHOKIDAR_USEPOLLING: "true"
