global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']

  - job_name: api-gateway
    static_configs:
      - targets: ['api-gateway:8000']
    metrics_path: /metrics

  - job_name: auth-service
    static_configs:
      - targets: ['auth-service:3006']
    metrics_path: /metrics

  - job_name: order-service
    static_configs:
      - targets: ['order-service:3001']
    metrics_path: /metrics

  - job_name: payment-service
    static_configs:
      - targets: ['payment-service:3002']
    metrics_path: /metrics

  - job_name: delivery-service
    static_configs:
      - targets: ['delivery-service:3003']
    metrics_path: /metrics

  - job_name: analytics-service
    static_configs:
      - targets: ['analytics-service:3004']
    metrics_path: /metrics

  - job_name: search-service
    static_configs:
      - targets: ['search-service:3005']
    metrics_path: /metrics

  - job_name: product-service
    static_configs:
      - targets: ['product-service:3007']
    metrics_path: /metrics
